const data = [
  {
    id: 0,
    name: "Nike",
    price: "1999",
    text: "Чоловіча вітровка найк Nike віндранер легкий від дощу біла",
    image: "nike.jpg",
  },
  {
    id: 1,
    name: "Asics gel kahana 8",
    price: "2700",
    text: "Чоловічі",
    image: "Asics gel kahana 8.jpg",
  },
  {
    id: 2,
    name: "широкі джинси",
    price: "1799",
    text: "Чоловічі",
    image: "jens.jpg",
  },
  {
    id: 3,
    name: "N12 - black",
    price: "2100",
    text: "Чоловічa",
    image: "n12.jpg",
  },
  {
    id: 4,
    name: "NIKE AIR MAX TERRASCAPE PLUS WHITE",
    price: "2699",
    text: "Чоловічі",
    image: "кроссовки.png",
  },
  {
    id: 5,
    name: "Чорна вітровка Arcteryx ",
    price: "1700",
    text: "+",
    image: "ветровка.png",
  },
  {
    id: 6,
    name: "NIKE NSW ESSENTIALS SLING BAG BLACK",
    price: "1199",
    text: "",
    image: "сумка.png",
  },
  {
    id: 7,
    name: "Asics Metarise Tokyo",
    price: "2899",
    text: "",
    image: "кросовки2.png",
  },
  {
    id: 8,
    name: " Stussy hoodie fuzzy dice",
    price: "2000",
    text: "",
    image: "худи.png",
  },
  {
    id: 9,
    name: "штани чорні",
    price: "999",
    text: "",
    image: "брюки.png",
  },
];
export default data;
